sudo: false

language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal test --haddock --no-haddock-deps
- export RootDir="$(stack path --project-roor)"

deploy:
  provider: pages
  local_dir: $RootDir/dash-server/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/doc/html/dash-server/
  skip-cleanup: true
  github-token: $TravisToken  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
